### ISSUE TITLE
A Big Issue About The Expansionary Mod Right Now And Other Mods

### ISSUE THREAD

**Issue by GitDrosTG** [Geezt435/Expansionary#1]
Ever Since Build 1.1.0 AKA The Map Creator Update, The Expansionary Mod Has Been Broken And Other Mods That Have Not Been Moved To The Map Creator Update Have Been Totally Broken And Bugged, The Bugs Include The Following: Units Not Appearing At All Or When You Place Them Down They Are Set To The Default Wobbler Without Clothing At All, This Really Needs To Be Fixed Along With The Other Mods, The Mods Ive Seen This Happen To Is The Following So Far: Expansionary, And More.

**Comment by GitDrosTG** [comment]
Even All Of My Custom Factions Names Were Replaced With 3 Dots And Since The Mods Are Broken, Some Of The Modded Stuff On My Units Are Broken And Dont Exist, And A Couple Of Units I Do Have, THEY CANT EVEN GET SPAWNED DOWN

**Comment by Geezt435** [comment]
Yes I see this error

Unfortunately I can't fix it easily, same with all of my other mods, making it harder when you include I am the only one coding and manages the whole mod, not only that I have other 3 mods which I also need to take care of, in College, having issues with many personal problems, ext

Though don't worry, I'll try to fix them as always... somehow

As for your units, you could try and find any item you used related to them and delete the items from my mods, those will be fix it... probably

**Comment by GitDrosTG** [comment]
Thank You For The Response Geezt, I Will Make More Content Once The Mods Are Back Up And Running Again Like With The TLC x TABS Series Or Some Original Content Not Apart Of That Multi-Faction Of Units, Have A Good Day And I Hope You Will Have Time To Do More Work On The Mod At Some Point.
