### ISSUE TITLE
A big problem！

### ISSUE THREAD

**Issue by 11451419198hub** [Geezt435/Expansionary#2]
when i play this mod with 1.1.4，all unit have been turned in to wobbler

**Comment by 11451419198hub** [comment]
could you fix this？

**Comment by 11451419198hub** [comment]
are you there

**Comment by Geezt435** [comment]
I can't be 24/7 active bruh

It is broken in 1.1.4, confirmed, sadly can't fix it rn, but I'll fix it when this 2nd Semester of University done during the holidays

**Comment by Geezt435** [comment]
okay fixed lol
